name: Portal Deployment

on: workflow_dispatch

permissions:
    id-token: write   # This is required for requesting the JWT
    contents: read 

jobs:
  Build_Code:
    runs-on: ubuntu-latest
    environment: AWS Production
    name: Portal - Build
    steps:
      #1. Checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      #2. Setup Node
      - name: Setup NodeJs 
        uses: actions/setup-node@v3
        with:
          node-version: '20.12.2'

      # 3. Build Angular
      - name: Build Angular Application
        run: |
          ls
          npm install -g @angular/cli
          npm install
          ng build --configuration production

      #4. Upload Build Artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
            name: my-portal-artifact
            path: ./dist/
            retention-days: 7
            overwrite: true

  Deploy:
    runs-on: ubuntu-latest
    environment: AWS Production
    name: Portal - Deploy
    needs: Build_Code
    steps:
      #1. Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.ASSUME_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.AWS_REGION }}

      #2. Download the artefact
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with: 
          name: my-portal-artifact
          path: ./dist/
          
      #3. Copy to S3 bucket.
      - name: Copy to S3 Bucket
        run: |
          aws s3 sync ./dist/my-portal/browser/ ${{ secrets.PORTFOLIO_S3_BUCKET_URL }}
