name: Portal Deployment

on: workflow_dispatch

env:
  AWS_REGION : "us-east-1"

permissions:
    id-token: write   # This is required for requesting the JWT
    contents: read 

jobs:
  Build_and_Deploy_Portal:
    runs-on: ubuntu-latest
    name: Portal - Build & Deploy
    steps:
      #1. Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::467490934638:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      
      #2. Checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      #3. Setup Node
      - name: Setup NodeJs 
        uses: actions/setup-node@v3
        with:
          node-version: '20.12.2'

      # 5. Build Angular
      - name: Build Angular Application
        run: |
          ls
          npm install -g @angular/cli
          npm install
          ng build

      # 6. Copy to S3 bucket.
      - name: Copy to S3 Bucket
        run: |
          aws s3 cp ./dist/* s3://467490934638-test
